# .kodiak.toml
# Minimal config. version is the only required field.
version = 1

[merge]
automerge_label = "automerge" # default: "automerge"
require_automerge_label = true


method = "merge"
delete_branch_on_merge = true
